var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};
$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var c=$jscomp.propertyToPolyfillSymbol[b];if(null==c)return a[b];c=a[c];return void 0!==c?c:a[b]};$jscomp.polyfill=function(a,b,c,d){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,c,d):$jscomp.polyfillUnisolated(a,b,c,d))};
$jscomp.polyfillUnisolated=function(a,b,c,d){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var f=a[d];f in c||(c[f]={});c=c[f]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,c,d){var f=a.split(".");a=1===f.length;d=f[0];d=!a&&d in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var e=0;e<f.length-1;e++){var k=f[e];k in d||(d[k]={});d=d[k]}f=f[f.length-1];c=$jscomp.IS_SYMBOL_NATIVE&&"es6"===c?d[f]:null;b=b(c);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,f,{configurable:!0,writable:!0,value:b}):b!==c&&($jscomp.propertyToPolyfillSymbol[f]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(f):$jscomp.POLYFILL_PREFIX+f,f=$jscomp.propertyToPolyfillSymbol[f],
$jscomp.defineProperty(d,f,{configurable:!0,writable:!0,value:b})))};$jscomp.polyfill("Math.sign",function(a){return a?a:function(a){a=Number(a);return 0===a||isNaN(a)?a:0<a?1:-1}},"es6","es3");$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.initSymbol=function(){};
$jscomp.polyfill("Symbol",function(a){if(a)return a;var b=function(a,b){this.$jscomp$symbol$id_=a;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:b})};b.prototype.toString=function(){return this.$jscomp$symbol$id_};var c=0,d=function(a){if(this instanceof d)throw new TypeError("Symbol is not a constructor");return new b("jscomp_symbol_"+(a||"")+"_"+c++,a)};return d},"es6","es3");$jscomp.initSymbolIterator=function(){};
$jscomp.polyfill("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=$jscomp.global[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&$jscomp.defineProperty(d.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return a},"es6",
"es3");$jscomp.initSymbolAsyncIterator=function(){};$jscomp.iteratorPrototype=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a};$jscomp.iteratorFromArray=function(a,b){a instanceof String&&(a+="");var c=0,d={next:function(){if(c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d};
$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6","es3");$jscomp.objectCreate=$jscomp.ASSUME_ES5||"function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b};
$jscomp.construct=function(){function a(){function a(){}new a;Reflect.construct(a,[],function(){});return new a instanceof a}if($jscomp.TRUST_ES6_POLYFILLS&&"undefined"!=typeof Reflect&&Reflect.construct){if(a())return Reflect.construct;var b=Reflect.construct;return function(a,d,f){a=b(a,d);f&&Reflect.setPrototypeOf(a,f.prototype);return a}}return function(a,b,f){void 0===f&&(f=a);f=$jscomp.objectCreate(f.prototype||Object.prototype);return Function.prototype.apply.call(a,f,b)||f}}();
$jscomp.polyfill("Reflect.construct",function(a){return $jscomp.construct},"es6","es3");$jscomp.findInternal=function(a,b,c){a instanceof String&&(a=String(a));for(var d=a.length,f=0;f<d;f++){var e=a[f];if(b.call(c,e,f,a))return{i:f,v:e}}return{i:-1,v:void 0}};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,c){return $jscomp.findInternal(this,a,c).v}},"es6","es3");$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},b={};try{return b.__proto__=a,b.a}catch(c){}return!1};
$jscomp.setPrototypeOf=$jscomp.TRUST_ES6_POLYFILLS&&"function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null;$jscomp.polyfill("Object.setPrototypeOf",function(a){return a||$jscomp.setPrototypeOf},"es6","es5");
$jscomp.polyfill("Array.from",function(a){return a?a:function(a,c,d){c=null!=c?c:function(a){return a};var b=[],e="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];if("function"==typeof e){a=e.call(a);for(var k=0;!(e=a.next()).done;)b.push(c.call(d,e.value,k++))}else for(e=a.length,k=0;k<e;k++)b.push(c.call(d,a[k],k));return b}},"es6","es3");
(function(){function a(b,c,d){function f(g,l){if(!c[g]){if(!b[g]){var h="function"==typeof require&&require;if(!l&&h)return h(g,!0);if(e)return e(g,!0);l=Error("Cannot find module '"+g+"'");throw l.code="MODULE_NOT_FOUND",l;}l=c[g]={exports:{}};b[g][0].call(l.exports,function(a){return f(b[g][1][a]||a)},l,l.exports,a,b,c,d)}return c[g].exports}for(var e="function"==typeof require&&require,k=0;k<d.length;k++)f(d[k]);return f}return a})()({1:[function(a,b,c){b=a("@babel/runtime/helpers/interopRequireDefault");
Object.defineProperty(c,"__esModule",{value:!0});c.default=void 0;a=new (b(a("../../library/background.js")).default)(["assets/underwater-fantasy-files/PNG/layers/sand.png"]);a.parallaxFactor=.25;c.default=a},{"../../library/background.js":19,"@babel/runtime/helpers/interopRequireDefault":39}],2:[function(a,b,c){b=a("@babel/runtime/helpers/interopRequireDefault");Object.defineProperty(c,"__esModule",{value:!0});c.default=void 0;a=new (b(a("../../library/background.js")).default)(["assets/underwater-fantasy-files/PNG/layers/far.png"]);
a.parallaxFactor=.2;c.default=a},{"../../library/background.js":19,"@babel/runtime/helpers/interopRequireDefault":39}],3:[function(a,b,c){b=a("@babel/runtime/helpers/interopRequireDefault");Object.defineProperty(c,"__esModule",{value:!0});c.default=void 0;a=new (b(a("../../library/background.js")).default)(["assets/underwater-fantasy-files/PNG/layers/foreground-2.png","assets/underwater-fantasy-files/PNG/layers/foreground-1.png"]);a.parallaxFactor=1;a.debugmode=!0;c.default=a},{"../../library/background.js":19,
"@babel/runtime/helpers/interopRequireDefault":39}],4:[function(a,b,c){var d=a("@babel/runtime/helpers/interopRequireDefault");Object.defineProperty(c,"__esModule",{value:!0});c.default=c.anotherFloor=void 0;b=d(a("../../library/character.js"));var f=d(a("../../library/collider.js")),e=d(a("../../library/spritesheet.js")),k=a("../../library/kinetics.js");d=d(a("./octopus.js"));var g=a("../../library/canvas.js");a=new b.default(new k.Kinetics(void 0,0,0),new f.default("floor",void 0,20*g.cw,40,0,0),
void 0,500,300,function(){this.motion.x=10*-g.cw;this.motion.y=g.ch-10});b=new b.default(new k.Kinetics(void 0,3*g.cw+400,340),new f.default("floor",void 0,200,40,200,20),new e.default("assets/platform1.png",1,{height:.5,width:1}),200,40);c.anotherFloor=b;d.default.registerCollisionWith(a.colliders[0]);d.default.registerCollisionWith(b.colliders[0]);c.default=a},{"../../library/canvas.js":21,"../../library/character.js":22,"../../library/collider.js":23,"../../library/kinetics.js":27,"../../library/spritesheet.js":30,
"./octopus.js":7,"@babel/runtime/helpers/interopRequireDefault":39}],5:[function(a,b,c){var d=a("@babel/runtime/helpers/interopRequireDefault");Object.defineProperty(c,"__esModule",{value:!0});c.default=void 0;var f=d(a("./octopus.js"));b=d(a("../../library/character.js"));var e=a("../../library/kinetics.js"),k=d(a("../../library/collider.js")),g=d(a("../../library/spritesheet.js"));a=d(a("./floor.js"));var l=1,h=!1;b=new b.default(new e.Kinetics(function(){var a=f.default.motion;a.x>this.x+10?(h=
-1===l?!0:!1,this.x+=1,l=this.xdirection=1):a.x<this.x-10?(h=1===l?!0:!1,--this.x,l=this.xdirection=-1):h=!1;h&&(this.angle*=-1);a.y>this.y?this.y+=1:a.y<this.y&&--this.y;var b=0;this.y!==a.y&&(b=Math.atan((a.y-this.y)/(a.x-this.x)));Math.abs(b)>Math.PI/4&&Math.abs(b)<2*Math.PI?b=Math.sign(b)*Math.PI/4:Math.abs(b)>Math.PI/2&&Math.abs(b)<3*Math.PI/4&&(b=Math.sign(b)*Math.PI*3/4);this.angle=this.angle<b?this.angle+.01:this.angle-.01}),new k.default("fish",void 0,40,40,20,20),new g.default("assets/fishSprite.png",
16,{height:.5,width:.5}),110,100,function(){this.registerAnimation("eat",new g.default("assets/fishSpriteEat.png",10));this.motion.y=100;this.motion.x=300;this.runAnimation("base",!0,200);this.alreadyCollided=!1});f.default.registerCollisionWith(b.colliders[0]);b.registerCollisionWith(a.default.colliders[0]);b.registerCollisionWith(f.default.colliders[0]);b.collideActions.floor=function(a,b,d){b.resolveCollisionHard(d)};b.alreadyCollided=!1;b.collideActions.octopus=function(){var a=this;console.log("eat");
this.alreadyCollided||this.runAnimation("eat",!0,100,function(){a.alreadyCollided=!0});this.alreadyCollided=!0};c.default=b},{"../../library/character.js":22,"../../library/collider.js":23,"../../library/kinetics.js":27,"../../library/spritesheet.js":30,"./floor.js":4,"./octopus.js":7,"@babel/runtime/helpers/interopRequireDefault":39}],6:[function(a,b,c){var d=a("@babel/runtime/helpers/interopRequireDefault");Object.defineProperty(c,"__esModule",{value:!0});c.default=c.niravko=void 0;d(a("./octopus.js"));
b=d(a("../../library/character.js"));var f=a("../../library/kinetics.js"),e=d(a("../../library/collider.js"));d=d(a("../../library/spritesheet.js"));a=a("../../library/canvas.js");a=new b.default(new f.Kinetics(void 0,3*a.cw+1E3,a.ch-104),new e.default("niravko.com",void 0,100,208,50,104),new d.default("assets/balloonlast.png"),100,208);c.niravko=a;c.default=a},{"../../library/canvas.js":21,"../../library/character.js":22,"../../library/collider.js":23,"../../library/kinetics.js":27,"../../library/spritesheet.js":30,
"./octopus.js":7,"@babel/runtime/helpers/interopRequireDefault":39}],7:[function(a,b,c){var d=a("@babel/runtime/helpers/interopRequireDefault");Object.defineProperty(c,"__esModule",{value:!0});c.default=void 0;b=d(a("../../library/character.js"));var f=d(a("../../library/collider.js")),e=d(a("../../library/spritesheet.js")),k=a("../../library/kinetics.js"),g=a("../../library/canvas.js");a("../../library/constants.js");var l=d(a("../../library/events.js"));a=d(a("../particles/bubbles.js"));var h=new b.default(new k.PhysicsKinetics,
new f.default("octopus",void 0,40,40,20,20),new e.default("assets/octoAnimOneWhite.png",12,{height:.5,width:.5}),100,100,function(){this.lastCollision="none";this.motion.reset();this.motion.x=g.cw/2;this.motion.y=g.ch/3;this.runAnimation("idle",!0,200)},function(){this.bubbleEmitter.dismantle()});c.default=h;h.bubbleEmitter=a.default;h.bubbleEmitter.motion=h.motion;h.registerAnimation("walk",new e.default("assets/octopusWalkWhite.png",8));h.registerAnimation("sit",new e.default("assets/idleOctopusWalk.png",
2));h.registerAnimation("idle",new e.default("assets/idleOctopusWhite.png",6));h.onFloor=!1;h.megaThrustAvailable=!0;h.thrusting=!1;h.thrust=function(){var a=this;if(!this.thrusting){this.thrusting=!0;this.runAnimation("base",!1,90,function(){return a.runAnimation("idle",!0,200)});var b=this.onFloor;window.setTimeout(function(){a.bubbleEmitter.emit();var d=b?0:a.motion.angle;a.motion.angle=d;a.motion.applyAcceleration(3,void 0,void 0,d)},180);window.setTimeout(function(){var d=b?0:a.motion.angle;
a.onFloor||a.motion.applyAcceleration(16,void 0,void 0,d);window.setTimeout(function(){return a.bubbleEmitter.emit()},100);window.setTimeout(function(){console.log("thrusting not");a.thrusting=!1},400)},560)}};h.turn=function(a){var b=g.cw/2;this.onFloor?this.motion.angle=0:(a=(a.offsetX+b/2)%b/b,0<=a&&1>=a&&(this.motion.angle=-a*Math.PI*2+Math.PI),this.motion.xdirection=.5<a?-1:1)};var m=!1;h.move=function(a){var b=this;if(this.onFloor){var d=1;this.motion.xdirection=-1;"left"==a&&(this.motion.xdirection=
1,d=-1);this.motion.vx=d;if(!1===m)return m=!0,this.runAnimation("walk",!0),function(){m=!1;b.onFloor&&b.runAnimation("sit")}}};h.collideActions.NO_COLLISIONS=function(){this.onFloor&&(console.log("base"),this.thrusting||this.runAnimation("idle",!0,200),this.onFloor=!1)};h.collideActions.floor=function(a,b,d){b.resolveCollisionHard(d,a);2==a&&(this.onFloor||(console.log("sit"),this.runAnimation("sit",!0,500),this.motion.angle=0),this.onFloor=!0)};h.collideActions.fish=function(a,b,d){"level2"===sceneManager.curScene.name&&
"fish"!==this.lastCollision&&(this.pause(),setTimeout(function(){window.sceneManager.gotoScene("gameOver")},900),this.lastCollision="fish")};h.collideActions.vortex=function(){var a=this;"level1"===sceneManager.curScene.name&&"vortex"!==this.lastCollision&&(this.hide(),setTimeout(function(){a.pause()},300),setTimeout(function(){window.sceneManager.gotoScene("level2")},1200),this.lastCollision="vortex")};h.collideActions.powerup=function(){var a=this;"level2"===sceneManager.curScene.name&&(setTimeout(function(){a.pause()},
500),window.location.href="https://www.youtube.com/watch?v=dQw4w9WgXcQ")};h.collideActions["niravko.com"]=function(){var a=this;"level2"===sceneManager.curScene.name&&(setTimeout(function(){a.pause()},500),window.location.href="https://niravko.com/")};c=new l.default;c.subscribe(h,[{code:"Space",cb:function(){return h.thrust}},{code:"KeyD",cb:function(){return h.move("right")}},{code:"KeyA",cb:function(){return h.move("left")}},{code:"KeyZ",cb:function(){return h.thrust(!0)}}]);c.subscribe(void 0,
[{code:"Escape",cb:function(){return sceneManager.gotoScene("title")}}]);c.subscribeMouse(h,h.turn,"move");h.registerEvent(c)},{"../../library/canvas.js":21,"../../library/character.js":22,"../../library/collider.js":23,"../../library/constants.js":24,"../../library/events.js":26,"../../library/kinetics.js":27,"../../library/spritesheet.js":30,"../particles/bubbles.js":16,"@babel/runtime/helpers/interopRequireDefault":39}],8:[function(a,b,c){var d=a("@babel/runtime/helpers/interopRequireDefault");
Object.defineProperty(c,"__esModule",{value:!0});c.default=c.powerup=void 0;b=d(a("./octopus.js"));var f=d(a("../../library/character.js")),e=a("../../library/kinetics.js"),k=d(a("../../library/collider.js"));d=d(a("../../library/spritesheet.js"));a=a("../../library/canvas.js");a=new f.default(new e.Kinetics(void 0,3*a.cw+300,a.ch-40),new k.default("powerup",void 0,64,40,32,12),new d.default("assets/treasure.png"),64,64);c.powerup=a;b.default.registerCollisionWith(a.colliders[0]);c.default=a},{"../../library/canvas.js":21,
"../../library/character.js":22,"../../library/collider.js":23,"../../library/kinetics.js":27,"../../library/spritesheet.js":30,"./octopus.js":7,"@babel/runtime/helpers/interopRequireDefault":39}],9:[function(a,b,c){var d=a("@babel/runtime/helpers/interopRequireDefault");Object.defineProperty(c,"__esModule",{value:!0});c.vortexFG=c.vortex=void 0;b=d(a("../../library/character.js"));var f=d(a("../../library/collider.js")),e=d(a("../../library/spritesheet.js")),k=d(a("./octopus.js"));d=a("../../library/kinetics.js");
a=new b.default(new d.Kinetics,new f.default("vortex",void 0,20,100,0,50),new e.default("assets/vortexSpriteT.png",9,{height:.5,width:.5}),200,200,function(){this.motion.x=5E3;this.motion.y=350;this.runAnimation("base",!0,100)});c.vortex=a;a.registerCollider(new f.default("vortexField",void 0,200,100,200,50));a.registerCollisionWith(k.default.colliders[0]);k.default.registerCollisionWith(a.colliders[0]);b=new b.default(new d.Kinetics,void 0,new e.default("assets/vortexSpriteFGT.png",9,{height:.5,
width:.5}),80,200,function(){this.motion.x=5060;this.motion.y=350});c.vortexFG=b;b.baseAnimation.startAnim(100);var g=void 0,l=void 0;a.collideActions.octopus=function(a,b,d){"vortex"!==b.name&&"vortexField"===b.name&&(a=(b.motion.y-d.motion.y)/(b.motion.x-d.motion.x+1E-5)+Math.PI/2,a=Math.atan(a)+Math.PI/4,d.motion.angle=d.motion.angle>a?d.motion.angle-.15:d.motion.angle+.15,k.default.motion.applyAcceleration(.9,1,1,a),this.unregisterDebugAnnotation(g),this.unregisterDebugAnnotation(l),g=this.registerDebugAnnotation({type:"line",
x2:b.motion.x,y2:b.motion.y,x1:d.motion.x,y1:d.motion.y}),l=this.registerDebugAnnotation({type:"text",x:b.motion.x,y:b.motion.y,text:180*a/Math.PI}))};a.collideActions.NO_COLLISIONS=function(){this.unregisterDebugAnnotation(g);this.unregisterDebugAnnotation(l);l=g=void 0}},{"../../library/character.js":22,"../../library/collider.js":23,"../../library/kinetics.js":27,"../../library/spritesheet.js":30,"./octopus.js":7,"@babel/runtime/helpers/interopRequireDefault":39}],10:[function(a,b,c){function d(){"title"===
h.curScene.name?(0,e.clearCanvas)("#142d4d"):(0,e.clearCanvas)("#b6e7f0");h.nextStep();requestAnimationFrame(d)}var f=a("@babel/runtime/helpers/interopRequireDefault");b=f(a("../library/sceneManager.js"));var e=a("../library/canvas.js");c=f(a("./levels/level1.js"));var k=f(a("./levels/level2.js")),g=f(a("./levels/title.js")),l=f(a("./levels/help.js"));a=f(a("./levels/gameOver.js"));window.DEBUGMODE=!1;var h=window.sceneManager=new b.default;h.register("title",g.default);h.register("level1",c.default);
h.register("level2",k.default);h.register("help",l.default);h.register("gameOver",a.default);window.bgMusic=new Audio("assets/mozartClarinet.mp3");window.onload=d},{"../library/canvas.js":21,"../library/sceneManager.js":29,"./levels/gameOver.js":11,"./levels/help.js":12,"./levels/level1.js":13,"./levels/level2.js":14,"./levels/title.js":15,"@babel/runtime/helpers/interopRequireDefault":39}],11:[function(a,b,c){var d=a("@babel/runtime/helpers/interopRequireDefault");Object.defineProperty(c,"__esModule",
{value:!0});c.default=void 0;var f=d(a("../../library/SimpleText.js")),e=d(a("../../library/character.js")),k=d(a("../../library/spritesheet.js")),g=d(a("../../library/scene.js"));b=d(a("../../library/events.js"));var l=a("../../library/kinetics.js");d=d(a("../../library/camera.js"));a=a("../../library/canvas.js");d=new d.default(a.cw,a.ch);k=new e.default(new l.Kinetics(void 0,a.cw/2+20,200),void 0,new k.default("assets/title.png"),364,164);var h=new e.default(new l.Kinetics(void 0,a.cw/2,380),void 0,
new f.default("Game Over","Economica","#ff6a4f",""),40,200);f=new e.default(new l.Kinetics(void 0,a.cw/2,440),void 0,new f.default("> Play Again <","Economica","#ff6a4f","bold"),40,200);d.registerChar(k);d.registerChar(h);d.registerChar(f);g=new g.default(d);b=new b.default;b.subscribe(void 0,[{code:"Enter",cb:function(){return sceneManager.gotoScene("title")}}]);g.keyboard=b;c.default=g},{"../../library/SimpleText.js":17,"../../library/camera.js":20,"../../library/canvas.js":21,"../../library/character.js":22,
"../../library/events.js":26,"../../library/kinetics.js":27,"../../library/scene.js":28,"../../library/spritesheet.js":30,"@babel/runtime/helpers/interopRequireDefault":39}],12:[function(a,b,c){var d=a("@babel/runtime/helpers/interopRequireDefault");Object.defineProperty(c,"__esModule",{value:!0});c.default=void 0;var f=d(a("../../library/SimpleText.js")),e=d(a("../../library/character.js")),k=d(a("../../library/spritesheet.js")),g=d(a("../../library/scene.js"));b=d(a("../../library/events.js"));
var l=a("../../library/kinetics.js");d=d(a("../../library/camera.js"));a=a("../../library/canvas.js");d=new d.default(a.cw,a.ch);k=new e.default(new l.Kinetics(void 0,a.cw/2+20,200),void 0,new k.default("assets/title.png"),364,164);var h=new e.default(new l.Kinetics(void 0,a.cw/2,340),void 0,new f.default("Help","Economica","#ff6a4f","bold"),40,200),m=new e.default(new l.Kinetics(void 0,a.cw/2,400),void 0,new f.default("Use Mouse to turn Octopus","Economica","#ff6a4f",""),40,600),n=new e.default(new l.Kinetics(void 0,
a.cw/2,440),void 0,new f.default("Press Space to propel forward","Economica","#ff6a4f",""),40,600),t=new e.default(new l.Kinetics(void 0,a.cw/2,480),void 0,new f.default("Press Z to propel harder","Economica","#ff6a4f",""),40,600);f=new e.default(new l.Kinetics(void 0,a.cw/2,540),void 0,new f.default("> Back <","Economica","#ff6a4f","bold"),40,300);d.registerChar(k);d.registerChar(h);d.registerChar(m);d.registerChar(n);d.registerChar(t);d.registerChar(f);g=new g.default(d);b=new b.default;b.subscribe(void 0,
[{code:"Enter",cb:function(){return sceneManager.gotoScene("title")}}]);g.keyboard=b;c.default=g},{"../../library/SimpleText.js":17,"../../library/camera.js":20,"../../library/canvas.js":21,"../../library/character.js":22,"../../library/events.js":26,"../../library/kinetics.js":27,"../../library/scene.js":28,"../../library/spritesheet.js":30,"@babel/runtime/helpers/interopRequireDefault":39}],13:[function(a,b,c){var d=a("@babel/runtime/helpers/interopRequireWildcard"),f=a("@babel/runtime/helpers/interopRequireDefault");
Object.defineProperty(c,"__esModule",{value:!0});c.default=void 0;var e=f(a("../../library/camera.js"));b=f(a("../../library/scene.js"));var k=a("../../library/canvas.js"),g=f(a("../characters/octopus.js")),l=d(a("../characters/floor.js"));f(a("../characters/followFish.js"));var h=a("../characters/vortex.js");d=f(a("../backgrounds/midBG.js"));var m=f(a("../backgrounds/backBG.js"));f(a("../backgrounds/lastBG.js"));f(a("../../library/character.js"));a("../../library/kinetics.js");f(a("../../library/SimpleText.js"));
var n=a("../../library/StaticRenderables.js");a=new e.default(k.cw,k.ch,50,50,g.default,void 0);a.followDirection="x";a=new b.default(a);a.startingCondition=function(){this.register(l.default);this.register(l.anotherFloor);this.register(h.vortex);this.register(g.default);var a=new n.StaticText("Use mouse to turn me and space to propel",k.cw/2,340,"Economica","#ff6a4f","",40),b=new n.StaticText("Getting the hang of it? Great!",3*k.cw/2,340,"Economica","#ff6a4f","",40),d=new n.StaticText("If on land use A and D to walk.",
3*k.cw,340,"Economica","#ff6a4f","",40);this.register(a);this.register(b);this.register(d);this.register(h.vortexFG)};a.registerBG(m.default);a.registerFG(d.default);c.default=a},{"../../library/SimpleText.js":17,"../../library/StaticRenderables.js":18,"../../library/camera.js":20,"../../library/canvas.js":21,"../../library/character.js":22,"../../library/kinetics.js":27,"../../library/scene.js":28,"../backgrounds/backBG.js":1,"../backgrounds/lastBG.js":2,"../backgrounds/midBG.js":3,"../characters/floor.js":4,
"../characters/followFish.js":5,"../characters/octopus.js":7,"../characters/vortex.js":9,"@babel/runtime/helpers/interopRequireDefault":39,"@babel/runtime/helpers/interopRequireWildcard":40}],14:[function(a,b,c){var d=a("@babel/runtime/helpers/interopRequireDefault");Object.defineProperty(c,"__esModule",{value:!0});c.default=void 0;var f=d(a("../../library/camera.js"));b=d(a("../../library/scene.js"));var e=a("../../library/canvas.js"),k=d(a("../characters/octopus.js")),g=d(a("../characters/floor.js")),
l=d(a("../characters/followFish.js")),h=a("../characters/vortex.js");d(a("../../library/character.js"));a("../../library/kinetics.js");d(a("../../library/SimpleText.js"));var m=a("../../library/StaticRenderables.js"),n=d(a("../characters/powerup.js"));d(a("../characters/niravko.js"));a=new f.default(e.cw,e.ch,50,50,k.default,void 0);a.followDirection="x";a=new b.default(a);a.startingCondition=function(){this.register(g.default);this.register(h.vortex);this.register(k.default);this.register(n.default);
this.register(l.default);var a=new m.StaticText("I don't want to work on this anymore.",e.cw/2,340,"Economica","#ff6a4f","",40),b=new m.StaticText("Keep running. Maybe you'll find something ...",3*e.cw/2,340,"Economica","#ff6a4f","",40);this.register(a);this.register(b);this.register(h.vortexFG)};c.default=a},{"../../library/SimpleText.js":17,"../../library/StaticRenderables.js":18,"../../library/camera.js":20,"../../library/canvas.js":21,"../../library/character.js":22,"../../library/kinetics.js":27,
"../../library/scene.js":28,"../characters/floor.js":4,"../characters/followFish.js":5,"../characters/niravko.js":6,"../characters/octopus.js":7,"../characters/powerup.js":8,"../characters/vortex.js":9,"@babel/runtime/helpers/interopRequireDefault":39}],15:[function(a,b,c){var d=a("@babel/runtime/helpers/interopRequireDefault");Object.defineProperty(c,"__esModule",{value:!0});c.default=void 0;var f=d(a("../../library/scene.js"));b=d(a("../../library/events.js"));var e=a("../../library/StaticRenderables.js");
d=d(a("../../library/camera.js"));a=a("../../library/canvas.js");d=new d.default(a.cw,a.ch);var k=(0,e.StaticTextGeneratorGenerator)("Economica","#ff6a4f","bold",40),g=[k("Filled",a.cw/2,380),k("up",a.cw/2,430),k("later",a.cw/2,480)];e=new e.StaticImage("assets/title.png",a.cw/2+20,200);d.registerChar(e);d.registerChar(g[0]);d.registerChar(g[1]);d.registerChar(g[2]);f=new f.default(d);var l={words:["Play Game","Sound Off","Help"],selected:0,sound:!1,onNext:function(){this.selected=(this.selected+
1)%this.words.length;this.update()},onPrev:function(){this.selected=(this.selected+this.words.length-1)%this.words.length;this.update()},update:function(){var a=this;g.forEach(function(b,d){a.selected===d?(b.setText("> "+a.words[d]+" <"),b.setProperty("bold")):(b.setText(a.words[d]),b.setProperty(""))})},activate:function(){var a=0<arguments.length&&void 0!==arguments[0]?arguments[0]:[];void 0!==a[this.selected]&&a[this.selected].bind(this)()},soundToggle:function(){this.sound=!this.sound;this.words[1]=
this.sound?"Sound On":"Sound Off";this.update()}};l.update();b=new b.default;b.subscribe(l,[{code:"ArrowUp",cb:l.onPrev},{code:"ArrowDown",cb:l.onNext},{code:"Enter",cb:function(){return l.activate([function(){return sceneManager.gotoScene("level1")},function(){l.soundToggle();this.sound?bgMusic.play():bgMusic.pause()},function(){return sceneManager.gotoScene("help")}])}}]);f.keyboard=b;c.default=f},{"../../library/StaticRenderables.js":18,"../../library/camera.js":20,"../../library/canvas.js":21,
"../../library/events.js":26,"../../library/scene.js":28,"@babel/runtime/helpers/interopRequireDefault":39}],16:[function(a,b,c){var d=a("@babel/runtime/helpers/interopRequireDefault");Object.defineProperty(c,"__esModule",{value:!0});c.default=void 0;b=d(a("../../library/emitter.js"));var f=a("../../library/kinetics.js"),e=d(a("../../library/collider.js"));a=d(a("../../library/spritesheet.js"));a=new b.default(void 0,[{motion:new f.PhysicsKinetics(-.07),sprite:new a.default("assets/bubble.png",10),
collider:new e.default,width:40,height:40,init:void 0,afterFn:function(a){a.runAnimation("base",!1,90,void 0,!1);a.motion.applyAcceleration(3*Math.random(),1,1,6*Math.random())}},{motion:new f.Kinetics(function(){--this.y;var a=Math.random();.7<a?this.x+=1:.3>a&&--this.x}),sprite:new a.default("assets/bubbleBig.png",14),collider:new e.default,width:40,height:40,init:void 0,afterFn:function(a){a.runAnimation("base",!1,90,!1)}}],1209,{min:1,max:5});c.default=a},{"../../library/collider.js":23,"../../library/emitter.js":25,
"../../library/kinetics.js":27,"../../library/spritesheet.js":30,"@babel/runtime/helpers/interopRequireDefault":39}],17:[function(a,b,c){b=a("@babel/runtime/helpers/interopRequireDefault");Object.defineProperty(c,"__esModule",{value:!0});c.default=void 0;var d=b(a("@babel/runtime/helpers/classCallCheck")),f=b(a("@babel/runtime/helpers/defineProperty")),e=a("./canvas.js");c.default=function m(a,b,c){var h=this,g=3<arguments.length&&void 0!==arguments[3]?arguments[3]:"",l=4<arguments.length?arguments[4]:
void 0;(0,d.default)(this,m);(0,f.default)(this,"text","");(0,f.default)(this,"font","");(0,f.default)(this,"color","");(0,f.default)(this,"property","");(0,f.default)(this,"size",void 0);(0,f.default)(this,"maxWidth",500);(0,f.default)(this,"draw",function(a,b){var d,c=2<arguments.length&&void 0!==arguments[2]?arguments[2]:0,f=3<arguments.length&&void 0!==arguments[3]?arguments[3]:1,g=4<arguments.length&&void 0!==arguments[4]?arguments[4]:1,l=5<arguments.length&&void 0!==arguments[5]?arguments[5]:
void 0,n=6<arguments.length?arguments[6]:void 0;n=null!==(d=n)&&void 0!==d?d:h.maxWidth;void 0===l&&(l=void 0===h.size?20:h.size);e.cc.save();e.cc.translate(a,b);0!==c&&e.cc.rotate(c);1!==f&&1!==g&&e.cc.scale(f,g);e.cc.font=h.property+" "+l+"px "+h.font;e.cc.fillStyle=h.color;e.cc.fillText(h.text,-e.cc.measureText(h.text).width/2,0,n);e.cc.restore()});this.text=a;this.font=b;c&&(this.color=c);this.property=g;this.size=l}},{"./canvas.js":21,"@babel/runtime/helpers/classCallCheck":34,"@babel/runtime/helpers/defineProperty":36,
"@babel/runtime/helpers/interopRequireDefault":39}],18:[function(a,b,c){b=a("@babel/runtime/helpers/interopRequireDefault");Object.defineProperty(c,"__esModule",{value:!0});c.StaticTextGeneratorGenerator=function(a,b,d,c){return function(e,h,f){return new l(e,h,f,a,b,d,c)}};c.StaticText=c.StaticImage=void 0;var d=b(a("@babel/runtime/helpers/classCallCheck")),f=b(a("@babel/runtime/helpers/createClass")),e=b(a("@babel/runtime/helpers/defineProperty")),k=b(a("./spritesheet.js")),g=b(a("./SimpleText.js"));
a=function(){function a(b,c,h){var f=3<arguments.length&&void 0!==arguments[3]?arguments[3]:void 0,l=4<arguments.length&&void 0!==arguments[4]?arguments[4]:void 0;(0,d.default)(this,a);(0,e.default)(this,"img",k.default);(0,e.default)(this,"x",void 0);(0,e.default)(this,"y",void 0);(0,e.default)(this,"height",void 0);(0,e.default)(this,"width",void 0);void 0!==b&&(this.img=new k.default(b),this.x=c,this.y=h,this.height=f,this.width=l)}(0,f.default)(a,[{key:"draw",value:function(a,b){this.img.draw(this.x+
a,this.y+b,0,1,1,this.width,this.height)}}]);return a}();c.StaticImage=a;var l=function(){function a(b,c,h,f,l){var n=5<arguments.length&&void 0!==arguments[5]?arguments[5]:"",m=6<arguments.length?arguments[6]:void 0;(0,d.default)(this,a);(0,e.default)(this,"text",g.default);(0,e.default)(this,"x",void 0);(0,e.default)(this,"y",void 0);(0,e.default)(this,"font",void 0);(0,e.default)(this,"text",g.default);this.text=new g.default(b,f,l,n,m);this.x=c;this.y=h}(0,f.default)(a,[{key:"init",value:function(){}},
{key:"nextStep",value:function(){}},{key:"dismantle",value:function(){}},{key:"setText",value:function(a){this.text.text=a}},{key:"setProperty",value:function(a){this.text.property=a}},{key:"draw",value:function(a,b){this.text.draw(this.x+a,this.y+b)}}]);return a}();c.StaticText=l},{"./SimpleText.js":17,"./spritesheet.js":30,"@babel/runtime/helpers/classCallCheck":34,"@babel/runtime/helpers/createClass":35,"@babel/runtime/helpers/defineProperty":36,"@babel/runtime/helpers/interopRequireDefault":39}],
19:[function(a,b,c){b=a("@babel/runtime/helpers/interopRequireDefault");Object.defineProperty(c,"__esModule",{value:!0});c.default=void 0;var d=b(a("@babel/runtime/helpers/slicedToArray")),f=b(a("@babel/runtime/helpers/classCallCheck")),e=b(a("@babel/runtime/helpers/createClass")),k=b(a("@babel/runtime/helpers/defineProperty")),g=a("./canvas.js");a=function(){function a(b,d,c,e,l){var h=this;(0,f.default)(this,a);(0,k.default)(this,"images",[]);(0,k.default)(this,"bgStack",[]);(0,k.default)(this,
"parallaxFactor",.2);(0,k.default)(this,"scale",1);(0,k.default)(this,"debugmode",!1);(0,k.default)(this,"nImgsLoaded",0);(0,k.default)(this,"allImgsLoaded",!1);(0,k.default)(this,"indexRight",0);(0,k.default)(this,"indexLeft",0);void 0!==b&&(b.forEach(function(a){var b=new Image;b.src=a;b.onload=function(){h.nImgsLoaded+=1;h.nImgsLoaded===h.images.length&&(h.allImgsLoaded=!0)};h.images.push(b)}),this.x=void 0===d?0:d,this.y=void 0===c?0:c,this.motionFunc=void 0===e?void 0:e,void 0!==l&&(this.parallaxFactor=
l))}(0,e.default)(a,[{key:"populateBgStack",value:function(){var a=0;if(this.allImgsLoaded)for(var b=0;b<=g.cw;){var d=this.images[a++%this.images.length];this.bgStack.push({img:d,x:b,y:"whatever"});b+=d.width*this.scale}}},{key:"setScale",value:function(){this.scale=0<arguments.length&&void 0!==arguments[0]?arguments[0]:1;this.populateBgStack()}},{key:"nextIndex",value:function(a){if(void 0===a)return 0;if("left"===a)return 0>this.indexLeft&&(this.indexLeft=0),this.indexLeft++%this.images.length;
if("right"===a)return 0>this.indexRight&&(this.indexRight=0),this.indexRight++%this.images.length}},{key:"decIndex",value:function(a){if(void 0===a)return 0;"left"===a?(--this.indexLeft,0>this.indexLeft&&(this.indexLeft=0)):"right"===a&&(--this.indexRight,0>this.indexRight&&(this.indexRight=0))}},{key:"draw",value:function(a,b){var c=this,e=2<arguments.length&&void 0!==arguments[2]?arguments[2]:2;if(void 0!==this.motionFunc){var h=this.motionFunc();h=(0,d.default)(h,2);a=h[0];b=h[1]}e!==this.scale&&
this.setScale(e);0===this.bgStack.length&&this.populateBgStack();a*=this.parallaxFactor;b*=this.parallaxFactor;h=this.bgStack[this.bgStack.length-1];var f=h.img.width*e;h.x+f<a+g.cw?this.bgStack.push({img:this.images[this.nextIndex("right")],x:h.x+f,y:"whatever"}):h.x>a+g.cw&&(this.decIndex("right"),this.bgStack.pop());h=this.bgStack[0];f=h.img.width*e;a>h.x+f?(this.decIndex("left"),this.bgStack.shift()):h.x>a&&this.bgStack.unshift({img:this.images[this.nextIndex("left")],x:h.x-f,y:"dontcare"});this.bgStack.forEach(function(b){var d=
b.img;void 0!==d&&(g.cc.save(),g.cc.translate(b.x-a-c.x,g.ch-d.height*e-c.y),g.cc.scale(e,e),g.cc.drawImage(d,0,0,d.width,d.height),g.cc.restore())})}}]);return a}();c.default=a},{"./canvas.js":21,"@babel/runtime/helpers/classCallCheck":34,"@babel/runtime/helpers/createClass":35,"@babel/runtime/helpers/defineProperty":36,"@babel/runtime/helpers/interopRequireDefault":39,"@babel/runtime/helpers/slicedToArray":45}],20:[function(a,b,c){b=a("@babel/runtime/helpers/interopRequireDefault");Object.defineProperty(c,
"__esModule",{value:!0});c.default=void 0;var d=b(a("@babel/runtime/helpers/classCallCheck")),f=b(a("@babel/runtime/helpers/createClass")),e=b(a("@babel/runtime/helpers/defineProperty")),k=b(a("./character.js"));a=function(){function a(b,c){var h=2<arguments.length&&void 0!==arguments[2]?arguments[2]:0,f=3<arguments.length&&void 0!==arguments[3]?arguments[3]:0,l=4<arguments.length&&void 0!==arguments[4]?arguments[4]:void 0,g=5<arguments.length&&void 0!==arguments[5]?arguments[5]:void 0,r=6<arguments.length&&
void 0!==arguments[6]?arguments[6]:0;(0,d.default)(this,a);(0,e.default)(this,"elements",[]);(0,e.default)(this,"offsetX",0);(0,e.default)(this,"offsetY",0);(0,e.default)(this,"frameWidth",void 0);(0,e.default)(this,"frameHeight",void 0);(0,e.default)(this,"follow",k.default);(0,e.default)(this,"followSpeed",void 0);(0,e.default)(this,"followDirection","xy");(0,e.default)(this,"cameraMotion",void 0);(0,e.default)(this,"x",void 0);(0,e.default)(this,"y",void 0);(0,e.default)(this,"backgrounds",[]);
(0,e.default)(this,"foregrounds",[]);this.frameWidth=b;this.frameHeight=c;this.follow=l;this.x=h;this.y=f;this.cameraMotion=g;this.followSpeed=r;this.init=function(){this.x=h;this.y=f}}(0,f.default)(a,[{key:"dismantle",value:function(){this.elements=[]}},{key:"registerChar",value:function(a){this.elements.push(a);return this.elements.length-1}},{key:"unregisterChar",value:function(a){delete this.elements[a]}},{key:"withinBounds",value:function(a){return!0}},{key:"renderFrame",value:function(){var a=
this;this.cameraMotion&&this.cameraMotion();if(this.follow){if("x"===this.followDirection||"xy"===this.followDirection)this.follow.motion.x-this.x>2*this.frameWidth/3?this.x=0<this.followSpeed?this.x+this.followSpeed:this.x+this.follow.motion.vx:this.follow.motion.x-this.x<this.frameWidth/3&&(this.x=0<this.followSpeed?this.x-this.followSpeed:this.x+this.follow.motion.vx);if("y"===this.followDirection||"xy"===this.followDirection)this.follow.motion.y-this.y>2/3*this.frameHeight?this.y=0<this.followSpeed?
this.y+this.followSpeed:this.y+this.follow.motion.vy:this.follow.motion.y-this.y<this.frameHeight/3&&(this.y=0<this.followSpeed?this.y-this.followSpeed:this.y+this.follow.motion.vy)}this.backgrounds.forEach(function(b){b.draw(a.x,a.y)});this.elements.forEach(function(b){a.withinBounds(b.motion)&&(b===a.follow?(b.draw(-a.x,-a.y),DEBUGMODE&&(b.hasDebugAnnotations()&&b.debugDrawAnnotations(-a.x,-a.y),b.debugDrawCollider(-a.x,-a.y))):(b.draw(-a.x,-a.y),DEBUGMODE&&(b.hasDebugAnnotations&&b.hasDebugAnnotations()&&
b.debugDrawAnnotations(-a.x,-a.y),b.debugDrawCollider&&b.debugDrawCollider(-a.x,-a.y))))});this.foregrounds.forEach(function(b){b.draw(a.x,a.y)})}},{key:"registerBG",value:function(a){this.backgrounds.push(a)}},{key:"registerFG",value:function(a){this.foregrounds.push(a)}}]);return a}();c.default=a},{"./character.js":22,"@babel/runtime/helpers/classCallCheck":34,"@babel/runtime/helpers/createClass":35,"@babel/runtime/helpers/defineProperty":36,"@babel/runtime/helpers/interopRequireDefault":39}],21:[function(a,
b,c){Object.defineProperty(c,"__esModule",{value:!0});c.clearCanvas=function(){var a=0<arguments.length&&void 0!==arguments[0]?arguments[0]:"#000";d.save();d.fillStyle=a;d.fillRect(0,0,f,e);d.restore()};c.ch=c.cw=c.cc=c.canvas=void 0;a=document.getElementById("game");c.canvas=a;var d=a.getContext("2d");c.cc=d;d.imageSmoothingEnabled=!1;var f=a.clientWidth;c.cw=f;var e=a.clientHeight;c.ch=e},{}],22:[function(a,b,c){b=a("@babel/runtime/helpers/interopRequireDefault");Object.defineProperty(c,"__esModule",
{value:!0});c.default=void 0;var d=b(a("@babel/runtime/helpers/classCallCheck")),f=b(a("@babel/runtime/helpers/createClass")),e=b(a("@babel/runtime/helpers/defineProperty")),k=a("./kinetics.js"),g=a("./canvas.js");b(a("./spritesheet.js"));a=function(){function a(b,c,f){var h=3<arguments.length&&void 0!==arguments[3]?arguments[3]:void 0,g=4<arguments.length&&void 0!==arguments[4]?arguments[4]:void 0,l=5<arguments.length&&void 0!==arguments[5]?arguments[5]:void 0,n=6<arguments.length&&void 0!==arguments[6]?
arguments[6]:void 0;(0,d.default)(this,a);(0,e.default)(this,"width",void 0);(0,e.default)(this,"height",void 0);(0,e.default)(this,"colliders",[]);(0,e.default)(this,"collidesWith",[]);(0,e.default)(this,"collideActions",[]);(0,e.default)(this,"animations",[]);(0,e.default)(this,"spriteOffset",{x:0,y:0});(0,e.default)(this,"baseAnimation",void 0);(0,e.default)(this,"motion",k.Kinetics);(0,e.default)(this,"initFn",void 0);(0,e.default)(this,"paused",!0);(0,e.default)(this,"hidden",!1);(0,e.default)(this,
"keyboard",void 0);(0,e.default)(this,"startingVariables",void 0);(0,e.default)(this,"animationRunning",!1);(0,e.default)(this,"debugAnnotations",[]);c&&(c.motion=b);this.motion=b;this.colliders[0]=c;this.baseAnimation=f;this.animations[0]=f;this.animations.base=f;this.width=h;this.height=g;void 0!==l&&(this.initFn=l.bind(this));void 0!==n&&(this.disinitFn=n.bind(this));this.startingVariables={x:b.x,y:b.y}}(0,f.default)(a,[{key:"registerCollider",value:function(a){a&&void 0!==a&&(a.motion=this.motion,
this.colliders.push(a))}},{key:"registerCollisionWith",value:function(a){this.collidesWith.push(a)}},{key:"registerAnimation",value:function(a,b){this.animations[a]=b}}]);(0,f.default)(a,[{key:"clone",value:function(){return new a(this.motion.clone(),this.colliders[0].clone(),this.baseAnimation.clone(),this.width,this.height)}},{key:"init",value:function(){this.unpause();this.unhide();this.motion.x=this.startingVariables.x;this.motion.y=this.startingVariables.y;void 0!==this.initFn&&this.initFn()}},
{key:"dismantle",value:function(){this.pause();void 0!==this.disinitFn&&this.disinitFn()}},{key:"nextStep",value:function(){this.paused||(this.motion.computePhysics(),this.checkCollisions())}},{key:"pause",value:function(){this.paused=!0;void 0!==this.keyboard&&this.keyboard.disarm()}},{key:"unpause",value:function(){this.paused=!1;void 0!==this.keyboard&&this.keyboard.arm()}},{key:"hide",value:function(){this.hidden=!0}},{key:"unhide",value:function(){this.hidden=!1}},{key:"draw",value:function(){var a=
0<arguments.length&&void 0!==arguments[0]?arguments[0]:0,b=1<arguments.length&&void 0!==arguments[1]?arguments[1]:0;this.hidden||void 0===this.baseAnimation||this.baseAnimation.draw(this.motion.x+a+this.spriteOffset.x,this.motion.y+b+this.spriteOffset.y,this.motion.angle,this.motion.xdirection,this.motion.ydirection,this.width,this.height)}},{key:"checkCollisions",value:function(){var a=this,b=!0;this.colliders.forEach(function(d){a.collidesWith.forEach(function(c){d.isColliding(c)&&(b=!1,void 0!==
a.collideActions[c.name]&&a.collideActions[c.name].bind(a)(d.collisionDirection(c),d,c))})});b&&this.collideActions.NO_COLLISIONS&&this.collideActions.NO_COLLISIONS.bind(this)()}},{key:"runAnimation",value:function(){var a=this,b=0<arguments.length&&void 0!==arguments[0]?arguments[0]:"base",d=2<arguments.length&&void 0!==arguments[2]?arguments[2]:100,c=3<arguments.length?arguments[3]:void 0,e=4<arguments.length&&void 0!==arguments[4]?arguments[4]:!0;!1===(1<arguments.length&&void 0!==arguments[1]?
arguments[1]:!1)?(this.baseAnimation.disengage(),this.baseAnimation=this.animations[b],this.baseAnimation.engage(),this.baseAnimation.startAnimOneShot(d,function(){e&&a.baseAnimation.resetFrame();c&&c.bind(a)()})):(this.baseAnimation.disengage(),this.baseAnimation=this.animations[b],this.baseAnimation.engage(),this.baseAnimation.startAnim(d))}},{key:"stopAnimation",value:function(){this.baseAnimation.stopAnim()}},{key:"setSprite",value:function(){var a=0<arguments.length&&void 0!==arguments[0]?arguments[0]:
"base";this.baseAnimation.resetFrame();this.baseAnimation=this.animations[a]}},{key:"registerEvent",value:function(a){this.keyboard=a;this.paused||this.keyboard.arm()}},{key:"debugDrawCollider",value:function(a,b){var d=this;this.colliders.forEach(function(c){void 0!==c&&(g.cc.save(),g.cc.fillStyle="rgba(0,0,0,0)",g.cc.lineWidth="1",g.cc.strokeStyle="white",g.cc.strokeRect(d.motion.x-c.offsetX+a,d.motion.y-c.offsetY+b,c.width,c.height),g.cc.fillStyle="white",g.cc.fillRect(d.motion.x+a,d.motion.y+
b,3,3),g.cc.fillStyle="red",g.cc.fillRect(d.motion.x+a,d.motion.y+b+3,3,3),g.cc.restore())})}},{key:"registerDebugAnnotation",value:function(a){return this.debugAnnotations.push(a)-1}},{key:"unregisterDebugAnnotation",value:function(a){void 0!==a&&delete this.debugAnnotations[a]}},{key:"hasDebugAnnotations",value:function(){return 0!==this.debugAnnotations.filter(function(a){return a}).length}},{key:"debugDrawAnnotations",value:function(a,b){g.cc.save();g.cc.strokeStyle="white";g.cc.fillStyle="white";
this.debugAnnotations.forEach(function(d){"line"===d.type?(g.cc.beginPath(),g.cc.moveTo(d.x1+a,d.y1+b),g.cc.lineTo(d.x2+a,d.y2+b),g.cc.stroke()):"text"===d.type&&g.cc.fillText(d.text,d.x+a,d.y+b)});g.cc.restore()}}]);return a}();c.default=a},{"./canvas.js":21,"./kinetics.js":27,"./spritesheet.js":30,"@babel/runtime/helpers/classCallCheck":34,"@babel/runtime/helpers/createClass":35,"@babel/runtime/helpers/defineProperty":36,"@babel/runtime/helpers/interopRequireDefault":39}],23:[function(a,b,c){function d(a,
b){var d=Object.keys(a);if(Object.getOwnPropertySymbols){var c=Object.getOwnPropertySymbols(a);b&&(c=c.filter(function(b){return Object.getOwnPropertyDescriptor(a,b).enumerable}));d.push.apply(d,c)}return d}function f(a){for(var b=1;b<arguments.length;b++){var c=null!=arguments[b]?arguments[b]:{};b%2?d(Object(c),!0).forEach(function(b){(0,g.default)(a,b,c[b])}):Object.getOwnPropertyDescriptors?Object.defineProperties(a,Object.getOwnPropertyDescriptors(c)):d(Object(c)).forEach(function(b){Object.defineProperty(a,
b,Object.getOwnPropertyDescriptor(c,b))})}return a}b=a("@babel/runtime/helpers/interopRequireDefault");Object.defineProperty(c,"__esModule",{value:!0});c.default=void 0;var e=b(a("@babel/runtime/helpers/classCallCheck")),k=b(a("@babel/runtime/helpers/createClass")),g=b(a("@babel/runtime/helpers/defineProperty")),l=a("./kinetics.js"),h=a("./constants.js");a=function(){function a(b,d,c,f,h,k){(0,e.default)(this,a);(0,g.default)(this,"name",String);(0,g.default)(this,"motion",l.Kinetics);(0,g.default)(this,
"width",void 0);(0,g.default)(this,"height",void 0);(0,g.default)(this,"offsetX",void 0);(0,g.default)(this,"offsetY",void 0);this.motion=d;this.width=c;this.height=f;this.offsetX=h;this.offsetY=k;this.name=b}(0,k.default)(a,[{key:"clone",value:function(a){void 0===a&&(a=this.motion.clone());return f(f({},this),{},{motion:a})}},{key:"isColliding",value:function(a){var b=this.motion.x-this.offsetX,d=this.motion.y-this.offsetY,c=this.width,e=this.height,f=a.motion.x-a.offsetX,g=a.motion.y-a.offsetY,
h=a.height;return b<f+a.width&&b+c>f&&d<g+h&&d+e>g?!0:!1}},{key:"collisionDirection",value:function(a){var b=this.motion.x-this.offsetX,d=this.motion.y-this.offsetY,c=this.width,e=this.height,f=a.motion.x-a.offsetX,g=a.motion.y-a.offsetY,h=a.width,l=[];l[0]=Math.abs(d-(g+a.height));l[1]=Math.abs(b+c-f);l[2]=Math.abs(d+e-g);l[3]=Math.abs(b-(f+h));var k=Math.min.apply(Math,l),n=0;l.forEach(function(a,b){a==k&&(n=b)});return n}},{key:"resolveCollisionLand",value:function(a,b){void 0===b&&(b=this.collisionDirection(a));
2==b?(this.motion.ay=0,this.motion.vy=0,this.motion.setY(a.motion.y-a.offsetY-(this.height-this.offsetY))):0==b?(this.motion.vy=0,this.motion.setY(a.motion.y-a.offsetY+a.height+this.offsetY)):3===b?this.motion.setX(a.motion.x-a.offsetX+a.width+this.offsetX):1==b&&this.motion.setX(a.motion.x-a.offsetX-this.offsetX)}},{key:"resolveCollisionHard",value:function(a,b){void 0===b&&(b=this.collisionDirection(a));2==b?(this.motion.ay=0,this.motion.vy=0,this.motion.setY(a.motion.y-a.offsetY-(this.height-this.offsetY))):
0==b?(this.motion.ay=h.physics.gravity,this.motion.vy=0,this.motion.setY(a.motion.y-a.offsetY+a.height+this.offsetY)):3===b?(this.motion.vx=0,this.motion.ax=1,this.motion.setX(a.motion.x-a.offsetX+a.width+this.offsetX)):1==b&&(this.motion.vx=0,this.motion.ax=-1,this.motion.setX(a.motion.x-a.offsetX-this.offsetX))}},{key:"resolveCollisionMoving",value:function(a){0==a.collisionDirection(this)?(this.motion.vx=1.25*a.motion.xdirection,this.motion.y=a.motion.y-this.height+14):2==a.collisionDirection(this)?
(this.motion.ay=h.physics.gravity,this.motion.vy=0,this.motion.y+=4):1==a.collisionDirection(this)?this.motion.x=a.motion.x+a.width+6:3==a.collisionDirection(this)&&(this.motion.x=a.motion.x-this.width)}}]);return a}();c.default=a},{"./constants.js":24,"./kinetics.js":27,"@babel/runtime/helpers/classCallCheck":34,"@babel/runtime/helpers/createClass":35,"@babel/runtime/helpers/defineProperty":36,"@babel/runtime/helpers/interopRequireDefault":39}],24:[function(a,b,c){Object.defineProperty(c,"__esModule",
{value:!0});c.physics={gravity:.06,decayMotion:.79};c.frameRateMs=75},{}],25:[function(a,b,c){b=a("@babel/runtime/helpers/interopRequireDefault");Object.defineProperty(c,"__esModule",{value:!0});c.default=void 0;var d=b(a("@babel/runtime/helpers/classCallCheck")),f=b(a("@babel/runtime/helpers/createClass")),e=b(a("@babel/runtime/helpers/defineProperty")),k=b(a("./character.js"));a=function(){function a(b,c){var f=2<arguments.length&&void 0!==arguments[2]?arguments[2]:1E3,g=3<arguments.length&&void 0!==
arguments[3]?arguments[3]:{min:1,max:3},h=4<arguments.length&&void 0!==arguments[4]?arguments[4]:{x:30,y:30};(0,d.default)(this,a);(0,e.default)(this,"motion",void 0);(0,e.default)(this,"particle",void 0);(0,e.default)(this,"decayTime",void 0);(0,e.default)(this,"curParticles",[]);this.motion=b;this.particle=c;this.decayTime=f;this.range=g;this.locationRange=h}(0,f.default)(a,[{key:"emit",value:function(){var a=this,b=this.range,d=this.locationRange;b=Math.floor(Math.random()*(b.max-b.min))+b.min;
for(var c=function(b){var c=Math.floor(Math.random()*d.x*2)-d.x,e=Math.floor(Math.random()*d.y*2)-d.y;b=a.particle[Math.floor(a.particle.length*Math.random())];void 0===b&&(console.log("the random indexing is producing out of range values prolly"),b=a.particle[0]);var f=b,g=f.collider,h=f.sprite,l=f.width,m=f.height,p=f.init;b=f.afterFn;f=f.motion.clone();f.x=a.motion.x+c;f.y=a.motion.y+e;c=void 0;void 0!==g&&(c=g.clone(f));e=h.clone();l=new k.default(f,c,e,l,m,p);var n=sceneManager.curScene.register(l);
b&&b(l);setTimeout(function(){sceneManager.curScene.unregister(n)},a.decayTime)},e=0;e<b;e++)c(e)}},{key:"dismantle",value:function(){}}]);return a}();c.default=a},{"./character.js":22,"@babel/runtime/helpers/classCallCheck":34,"@babel/runtime/helpers/createClass":35,"@babel/runtime/helpers/defineProperty":36,"@babel/runtime/helpers/interopRequireDefault":39}],26:[function(a,b,c){function d(a){var b=f();return function(){var d=(0,g.default)(a);if(b){var c=(0,g.default)(this).constructor;d=Reflect.construct(d,
arguments,c)}else d=d.apply(this,arguments);return(0,k.default)(this,d)}}function f(){if("undefined"===typeof Reflect||!Reflect.construct||Reflect.construct.sham)return!1;if("function"===typeof Proxy)return!0;try{return Date.prototype.toString.call(Reflect.construct(Date,[],function(){})),!0}catch(n){return!1}}b=a("@babel/runtime/helpers/interopRequireDefault");Object.defineProperty(c,"__esModule",{value:!0});c.default=void 0;var e=b(a("@babel/runtime/helpers/inherits")),k=b(a("@babel/runtime/helpers/possibleConstructorReturn")),
g=b(a("@babel/runtime/helpers/getPrototypeOf")),l=b(a("@babel/runtime/helpers/classCallCheck")),h=b(a("@babel/runtime/helpers/createClass")),m=b(a("@babel/runtime/helpers/defineProperty"));a=function(){function a(){var b=this;(0,l.default)(this,a);(0,m.default)(this,"subscribersKey",[]);(0,m.default)(this,"keyUpQueue",[]);(0,m.default)(this,"subscribersMouse",[]);(0,m.default)(this,"codesAlreadyRegistered",[]);(0,m.default)(this,"keyDown",function(a){b.subscribersKey.forEach(function(d){d.keyEvent.forEach(function(c){if(c.code==
a.code){a.preventDefault();var e=c.cb.bind(d.character)();void 0!==e&&void 0===b.codesAlreadyRegistered.find(function(a){return a===c.code})&&(b.keyUpQueue.push({code:c.code,cb:e,character:d.character}),b.codesAlreadyRegistered.push(c.code))}})})}.bind(this));(0,m.default)(this,"keyUp",function(a){b.keyUpQueue.forEach(function(d,c,e){a.code===d.code&&void 0!==d.cb&&(d.cb.bind(d.character)(a),e.splice(c,1),b.codesAlreadyRegistered=b.codesAlreadyRegistered.filter(function(b){return b!==a.code}))})}.bind(this));
(0,m.default)(this,"mouseMove",function(a){b.subscribersMouse.filter(function(a){return"move"==a.event}).forEach(function(b){return b.fn.bind(b.character)(a)})}.bind(this))}(0,h.default)(a,[{key:"arm",value:function(){window.addEventListener("keydown",this.keyDown);window.addEventListener("keyup",this.keyUp);window.addEventListener("mousemove",this.mouseMove)}},{key:"disarm",value:function(){window.removeEventListener("keydown",this.keyDown);window.removeEventListener("keyup",this.keyUp);window.removeEventListener("mousemove",
this.mouseMove)}},{key:"subscribe",value:function(a){this.subscribersKey.push({character:a,keyEvent:1<arguments.length&&void 0!==arguments[1]?arguments[1]:[]})}},{key:"subscribeMouse",value:function(a,b){var d=2<arguments.length&&void 0!==arguments[2]?arguments[2]:"move";"move"===d&&this.subscribersMouse.push({character:a,fn:b,event:d})}}]);return a}();c.default=a;(function(a){function b(){(0,l.default)(this,b);return c.apply(this,arguments)}(0,e.default)(b,a);var c=d(b);return b})(a);(function(a){function b(){(0,
l.default)(this,b);return c.apply(this,arguments)}(0,e.default)(b,a);var c=d(b);return b})(a)},{"@babel/runtime/helpers/classCallCheck":34,"@babel/runtime/helpers/createClass":35,"@babel/runtime/helpers/defineProperty":36,"@babel/runtime/helpers/getPrototypeOf":37,"@babel/runtime/helpers/inherits":38,"@babel/runtime/helpers/interopRequireDefault":39,"@babel/runtime/helpers/possibleConstructorReturn":43}],27:[function(a,b,c){function d(a){var b=f();return function(){var d=(0,m.default)(a);if(b){var c=
(0,m.default)(this).constructor;d=Reflect.construct(d,arguments,c)}else d=d.apply(this,arguments);return(0,h.default)(this,d)}}function f(){if("undefined"===typeof Reflect||!Reflect.construct||Reflect.construct.sham)return!1;if("function"===typeof Proxy)return!0;try{return Date.prototype.toString.call(Reflect.construct(Date,[],function(){})),!0}catch(v){return!1}}function e(a,b){var d=Object.keys(a);if(Object.getOwnPropertySymbols){var c=Object.getOwnPropertySymbols(a);b&&(c=c.filter(function(b){return Object.getOwnPropertyDescriptor(a,
b).enumerable}));d.push.apply(d,c)}return d}function k(a){for(var b=1;b<arguments.length;b++){var d=null!=arguments[b]?arguments[b]:{};b%2?e(Object(d),!0).forEach(function(b){(0,p.default)(a,b,d[b])}):Object.getOwnPropertyDescriptors?Object.defineProperties(a,Object.getOwnPropertyDescriptors(d)):e(Object(d)).forEach(function(b){Object.defineProperty(a,b,Object.getOwnPropertyDescriptor(d,b))})}return a}b=a("@babel/runtime/helpers/interopRequireDefault");Object.defineProperty(c,"__esModule",{value:!0});
c.PhysicsKineticsLand=c.PhysicsKinetics=c.Kinetics=void 0;var g=b(a("@babel/runtime/helpers/assertThisInitialized")),l=b(a("@babel/runtime/helpers/inherits")),h=b(a("@babel/runtime/helpers/possibleConstructorReturn")),m=b(a("@babel/runtime/helpers/getPrototypeOf")),n=b(a("@babel/runtime/helpers/classCallCheck")),t=b(a("@babel/runtime/helpers/createClass")),p=b(a("@babel/runtime/helpers/defineProperty")),r=a("./canvas.js"),q=a("./constants.js"),u=function(){function a(b){var d=1<arguments.length&&
void 0!==arguments[1]?arguments[1]:50,c=2<arguments.length&&void 0!==arguments[2]?arguments[2]:50;(0,n.default)(this,a);(0,p.default)(this,"x",50);(0,p.default)(this,"y",50);(0,p.default)(this,"xdirection",1);(0,p.default)(this,"ydirection",1);(0,p.default)(this,"angle",0);(0,p.default)(this,"origMotionFunction",void 0);(0,p.default)(this,"motionFunction",void 0);(0,p.default)(this,"last",this);b&&(this.origMotionFunction=b,this.motionFunction=b.bind(this));this.x=d;this.y=c}(0,t.default)(a,[{key:"clone",
value:function(){return new a(this.origMotionFunction,this.x,this.y)}},{key:"computePhysics",value:function(){this.saveLast();void 0!==this.motionFunction&&this.motionFunction()}},{key:"reset",value:function(){this.y=this.x=50;this.ydirection=this.xdirection=1;this.angle=0;this.saveLast()}},{key:"saveLast",value:function(){this.last=k({},this)}},{key:"setX",value:function(a){this.saveLast();this.x=a}},{key:"setY",value:function(a){this.saveLast();this.y=a}}]);return a}();c.Kinetics=u;a=function(a){function b(){var a=
0<arguments.length&&void 0!==arguments[0]?arguments[0]:q.physics.gravity;(0,n.default)(this,b);var d=c.call(this);(0,p.default)((0,g.default)(d),"angle",0);(0,p.default)((0,g.default)(d),"x",r.cw/2);(0,p.default)((0,g.default)(d),"y",r.ch/2);(0,p.default)((0,g.default)(d),"vx",0);(0,p.default)((0,g.default)(d),"vy",0);(0,p.default)((0,g.default)(d),"ax",0);(0,p.default)((0,g.default)(d),"ay",0);d.gravity=void 0!==a?a:q.physics.gravity;return d}(0,l.default)(b,a);var c=d(b);(0,t.default)(b,[{key:"clone",
value:function(){return new b(this.gravity)}},{key:"computePhysics",value:function(){this.saveLast();this.ay+=this.gravity;this.ay*=q.physics.decayMotion;this.ax*=q.physics.decayMotion;this.vy+=this.ay;this.vx+=this.ax;this.vy*=q.physics.decayMotion;this.vx*=q.physics.decayMotion;this.y+=this.vy;this.x+=this.vx}},{key:"applyAcceleration",value:function(a){var b=1<arguments.length&&void 0!==arguments[1]?arguments[1]:1,d=2<arguments.length&&void 0!==arguments[2]?arguments[2]:1,c=3<arguments.length?
arguments[3]:void 0;void 0===c&&(c=this.angle);this.saveLast();this.ax+=b*a*Math.sin(c);this.ay-=d*a*Math.cos(c)}},{key:"reset",value:function(){u.prototype.reset();this.vx=this.vy=this.ay=this.ax=0}}]);return b}(u);c.PhysicsKinetics=a;a=function(a){function b(){var a=0<arguments.length&&void 0!==arguments[0]?arguments[0]:q.physics.gravity;(0,n.default)(this,b);var d=c.call(this);(0,p.default)((0,g.default)(d),"angle",0);(0,p.default)((0,g.default)(d),"x",r.cw/2);(0,p.default)((0,g.default)(d),"y",
r.ch/2);(0,p.default)((0,g.default)(d),"vx",0);(0,p.default)((0,g.default)(d),"vy",0);(0,p.default)((0,g.default)(d),"ax",0);(0,p.default)((0,g.default)(d),"ay",0);d.gravity=void 0!==a?a:q.physics.gravity;return d}(0,l.default)(b,a);var c=d(b);(0,t.default)(b,[{key:"clone",value:function(){return new b(this.gravity)}},{key:"computePhysics",value:function(){this.saveLast();this.ay+=this.gravity;this.vy+=this.ay;this.vx+=this.ax;this.y+=this.vy;this.x+=this.vx}},{key:"applyAcceleration",value:function(a){var b=
1<arguments.length&&void 0!==arguments[1]?arguments[1]:1,d=2<arguments.length&&void 0!==arguments[2]?arguments[2]:1,c=3<arguments.length?arguments[3]:void 0;void 0===c&&(c=this.angle);this.saveLast();this.ax+=b*a*Math.sin(c);this.ay-=d*a*Math.cos(c)}},{key:"applyVelocity",value:function(a,b){void 0===b&&(b=this.angle);this.saveLast();this.vx+=a*Math.sin(b);this.vy-=a*Math.cos(b)}},{key:"reset",value:function(){u.prototype.reset();this.vx=this.vy=this.ay=this.ax=0}}]);return b}(u);c.PhysicsKineticsLand=
a},{"./canvas.js":21,"./constants.js":24,"@babel/runtime/helpers/assertThisInitialized":33,"@babel/runtime/helpers/classCallCheck":34,"@babel/runtime/helpers/createClass":35,"@babel/runtime/helpers/defineProperty":36,"@babel/runtime/helpers/getPrototypeOf":37,"@babel/runtime/helpers/inherits":38,"@babel/runtime/helpers/interopRequireDefault":39,"@babel/runtime/helpers/possibleConstructorReturn":43}],28:[function(a,b,c){b=a("@babel/runtime/helpers/interopRequireDefault");Object.defineProperty(c,"__esModule",
{value:!0});c.default=void 0;var d=b(a("@babel/runtime/helpers/classCallCheck")),f=b(a("@babel/runtime/helpers/createClass")),e=b(a("@babel/runtime/helpers/defineProperty")),k=b(a("./camera.js"));a=function(){function a(b){(0,d.default)(this,a);(0,e.default)(this,"characters",[]);(0,e.default)(this,"cam",k.default);(0,e.default)(this,"keyboard",void 0);(0,e.default)(this,"sceneIndexToCamIndex",[]);(0,e.default)(this,"backgrounds",[]);(0,e.default)(this,"foregrounds",[]);this.cam=b}(0,f.default)(a,
[{key:"initialize",value:function(){this.startingCondition&&this.startingCondition.bind(this)();this.cam.init();this.characters.forEach(function(a){a.init()});void 0!==this.keyboard&&this.keyboard.arm()}},{key:"dismantle",value:function(){var a=this;void 0!==this.keyboard&&this.keyboard.disarm();this.characters.forEach(function(b){a.cam.dismantle();b.dismantle()});this.characters=[]}},{key:"nextStep",value:function(){this.characters.forEach(function(a){a.nextStep()});this.cam.renderFrame()}},{key:"register",
value:function(a){a.init();this.characters.push(a);var b=this.characters.length-1;a=this.cam.registerChar(a);this.sceneIndexToCamIndex[b]=a;return b}},{key:"unregister",value:function(a){delete this.characters[a];this.cam.unregisterChar(this.sceneIndexToCamIndex[a])}},{key:"hasCharacter",value:function(a){return a.find(function(b){return b===a})?!0:!1}},{key:"registerBG",value:function(a){this.cam.registerBG(a)}},{key:"registerFG",value:function(a){this.cam.registerFG(a)}}]);return a}();c.default=
a},{"./camera.js":20,"@babel/runtime/helpers/classCallCheck":34,"@babel/runtime/helpers/createClass":35,"@babel/runtime/helpers/defineProperty":36,"@babel/runtime/helpers/interopRequireDefault":39}],29:[function(a,b,c){b=a("@babel/runtime/helpers/interopRequireDefault");Object.defineProperty(c,"__esModule",{value:!0});c.default=void 0;var d=b(a("@babel/runtime/helpers/classCallCheck")),f=b(a("@babel/runtime/helpers/createClass")),e=b(a("@babel/runtime/helpers/defineProperty"));a=function(){function a(){(0,
d.default)(this,a);(0,e.default)(this,"curScene",void 0);(0,e.default)(this,"scenes",[])}(0,f.default)(a,[{key:"register",value:function(a,b){b.name=a;void 0===this.curScene&&(this.curScene=b,this.curScene.initialize());this.scenes.push({name:a,scene:b})}},{key:"gotoScene",value:function(a){var b=this.scenes.find(function(b){return b.name===a});void 0===b?console.log("No such Scene"):(this.curScene.dismantle(),this.curScene=b.scene,this.curScene.initialize())}},{key:"nextStep",value:function(){this.curScene&&
this.curScene.nextStep()}},{key:"restart",value:function(){this.curScene.dismantle();this.curScene.initialize()}}]);return a}();c.default=a},{"@babel/runtime/helpers/classCallCheck":34,"@babel/runtime/helpers/createClass":35,"@babel/runtime/helpers/defineProperty":36,"@babel/runtime/helpers/interopRequireDefault":39}],30:[function(a,b,c){b=a("@babel/runtime/helpers/interopRequireDefault");Object.defineProperty(c,"__esModule",{value:!0});c.CompositeSpritesheet=c.default=void 0;var d=b(a("@babel/runtime/helpers/classCallCheck")),
f=b(a("@babel/runtime/helpers/createClass")),e=b(a("@babel/runtime/helpers/defineProperty")),k=a("./constants.js"),g=a("./canvas.js");a=function(){function a(b){var c=this,f=1<arguments.length&&void 0!==arguments[1]?arguments[1]:1,h=2<arguments.length&&void 0!==arguments[2]?arguments[2]:{height:.5,width:.5};(0,d.default)(this,a);(0,e.default)(this,"image",void 0);(0,e.default)(this,"sheetwidth",void 0);(0,e.default)(this,"sheetheight",void 0);(0,e.default)(this,"cols",void 0);(0,e.default)(this,"spritewidth",
void 0);(0,e.default)(this,"originFactor",void 0);(0,e.default)(this,"imageLoaded",!1);(0,e.default)(this,"draw",function(a,b){var d=2<arguments.length&&void 0!==arguments[2]?arguments[2]:0,e=3<arguments.length&&void 0!==arguments[3]?arguments[3]:1,f=4<arguments.length&&void 0!==arguments[4]?arguments[4]:1,h=5<arguments.length&&void 0!==arguments[5]?arguments[5]:void 0,k=6<arguments.length&&void 0!==arguments[6]?arguments[6]:void 0;void 0===h&&(h=c.image.width/c.cols);void 0===k&&(k=c.sheetheight);
a=Math.floor(a);b=Math.floor(b);void 0!==c.image&&(g.cc.save(),g.cc.translate(a,b),0!==d&&g.cc.rotate(d),1===e&&1===f||g.cc.scale(e,f),g.cc.drawImage(c.image,c.curFrame*c.spritewidth-1,0,c.spritewidth,c.sheetheight,-h*c.originFactor.width,-k*c.originFactor.height,h,k),g.cc.restore())});(0,e.default)(this,"curFrame",0);(0,e.default)(this,"animTimer",void 0);(0,e.default)(this,"alreadyAnimating",!1);(0,e.default)(this,"engaged",!1);(0,e.default)(this,"newFrame",function(){if(c.engaged){if(c.curFrame+
1>=c.cols)return"done";++c.curFrame}});(0,e.default)(this,"resetFrame",function(){c.curFrame=0}.bind(this));void 0!==b&&(this.image=new Image,this.image.src=b,this.cols=f,this.curFrame=0,this.originFactor=h,this.image.onload=function(){c.sheetwidth=c.image.width;c.sheetheight=c.image.height;c.spritewidth=c.sheetwidth/c.cols;c.imageLoaded=!0})}(0,f.default)(a,[{key:"clone",value:function(){if(this.imageLoaded){var b=new a;b.image=this.image;b.sheetheight=this.sheetheight;b.sheetwidth=this.sheetwidth;
b.spritewidth=this.spritewidth;b.originFactor=this.originFactor;b.cols=this.cols;return b}return new a(this.location,this.cols,this.originFactor)}},{key:"engage",value:function(){this.engaged=!0;this.resetFrame()}},{key:"disengage",value:function(){this.engaged=!1;this.resetFrame()}},{key:"startAnim",value:function(){var a=this,b=0<arguments.length&&void 0!==arguments[0]?arguments[0]:k.frameRateMs;this.engaged&&!this.alreadyAnimating&&(this.animTimer=setInterval(function(){"done"===a.newFrame()&&
a.resetFrame()},b),this.alreadyAnimating=!0)}},{key:"stopAnim",value:function(){clearInterval(this.animTimer);this.animTimer=void 0;this.resetFrame();this.alreadyAnimating=!1}},{key:"startAnimOneShot",value:function(){var a=this,b=0<arguments.length&&void 0!==arguments[0]?arguments[0]:k.frameRateMs,d=1<arguments.length&&void 0!==arguments[1]?arguments[1]:void 0;if(this.engaged&&!this.alreadyAnimating){this.alreadyAnimating=!0;var c=setInterval(function(){"done"===a.newFrame()&&(window.clearInterval(c),
a.alreadyAnimating=!1,d&&d())},b)}}},{key:"getSpriteWidth",value:function(){return this.image.width/this.cols}},{key:"getSpriteHeight",value:function(){return this.image.height}}]);return a}();c.default=a;a=function(){function a(){var b;(0,d.default)(this,a);(0,e.default)(this,"sprites",[]);(b=this.sprites).push.apply(b,arguments)}(0,f.default)(a,[{key:"draw",value:function(){var a=arguments;this.sprites.forEach(function(b){return b.draw.apply(b,a)})}}]);return a}();c.CompositeSpritesheet=a},{"./canvas.js":21,
"./constants.js":24,"@babel/runtime/helpers/classCallCheck":34,"@babel/runtime/helpers/createClass":35,"@babel/runtime/helpers/defineProperty":36,"@babel/runtime/helpers/interopRequireDefault":39}],31:[function(a,b,c){b.exports=function(a,b){if(null==b||b>a.length)b=a.length;for(var d=0,c=Array(b);d<b;d++)c[d]=a[d];return c}},{}],32:[function(a,b,c){b.exports=function(a){if(Array.isArray(a))return a}},{}],33:[function(a,b,c){b.exports=function(a){if(void 0===a)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");
return a}},{}],34:[function(a,b,c){b.exports=function(a,b){if(!(a instanceof b))throw new TypeError("Cannot call a class as a function");}},{}],35:[function(a,b,c){function d(a,b){for(var d=0;d<b.length;d++){var c=b[d];c.enumerable=c.enumerable||!1;c.configurable=!0;"value"in c&&(c.writable=!0);Object.defineProperty(a,c.key,c)}}b.exports=function(a,b,c){b&&d(a.prototype,b);c&&d(a,c);return a}},{}],36:[function(a,b,c){b.exports=function(a,b,c){b in a?Object.defineProperty(a,b,{value:c,enumerable:!0,
configurable:!0,writable:!0}):a[b]=c;return a}},{}],37:[function(a,b,c){function d(a){b.exports=d=Object.setPrototypeOf?Object.getPrototypeOf:function(a){return a.__proto__||Object.getPrototypeOf(a)};return d(a)}b.exports=d},{}],38:[function(a,b,c){var d=a("./setPrototypeOf");b.exports=function(a,b){if("function"!==typeof b&&null!==b)throw new TypeError("Super expression must either be null or a function");a.prototype=Object.create(b&&b.prototype,{constructor:{value:a,writable:!0,configurable:!0}});
b&&d(a,b)}},{"./setPrototypeOf":44}],39:[function(a,b,c){b.exports=function(a){return a&&a.__esModule?a:{"default":a}}},{}],40:[function(a,b,c){function d(){if("function"!==typeof WeakMap)return null;var a=new WeakMap;d=function(){return a};return a}var f=a("../helpers/typeof");b.exports=function(a){if(a&&a.__esModule)return a;if(null===a||"object"!==f(a)&&"function"!==typeof a)return{"default":a};var b=d();if(b&&b.has(a))return b.get(a);var c={},e=Object.defineProperty&&Object.getOwnPropertyDescriptor,
h;for(h in a)if(Object.prototype.hasOwnProperty.call(a,h)){var m=e?Object.getOwnPropertyDescriptor(a,h):null;m&&(m.get||m.set)?Object.defineProperty(c,h,m):c[h]=a[h]}c["default"]=a;b&&b.set(a,c);return c}},{"../helpers/typeof":46}],41:[function(a,b,c){b.exports=function(a,b){if("undefined"!==typeof Symbol&&Symbol.iterator in Object(a)){var d=[],c=!0,f=!1,l=void 0;try{for(var h=a[Symbol.iterator](),m;!(c=(m=h.next()).done)&&(d.push(m.value),!b||d.length!==b);c=!0);}catch(n){f=!0,l=n}finally{try{if(!c&&
null!=h["return"])h["return"]()}finally{if(f)throw l;}}return d}}},{}],42:[function(a,b,c){b.exports=function(){throw new TypeError("Invalid attempt to destructure non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method.");}},{}],43:[function(a,b,c){var d=a("../helpers/typeof"),f=a("./assertThisInitialized");b.exports=function(a,b){return!b||"object"!==d(b)&&"function"!==typeof b?f(a):b}},{"../helpers/typeof":46,"./assertThisInitialized":33}],44:[function(a,
b,c){function d(a,c){b.exports=d=Object.setPrototypeOf||function(a,b){a.__proto__=b;return a};return d(a,c)}b.exports=d},{}],45:[function(a,b,c){var d=a("./arrayWithHoles"),f=a("./iterableToArrayLimit"),e=a("./unsupportedIterableToArray"),k=a("./nonIterableRest");b.exports=function(a,b){return d(a)||f(a,b)||e(a,b)||k()}},{"./arrayWithHoles":32,"./iterableToArrayLimit":41,"./nonIterableRest":42,"./unsupportedIterableToArray":47}],46:[function(a,b,c){function d(a){"@babel/helpers - typeof";b.exports=
"function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?d=function(a){return typeof a}:d=function(a){return a&&"function"===typeof Symbol&&a.constructor===Symbol&&a!==Symbol.prototype?"symbol":typeof a};return d(a)}b.exports=d},{}],47:[function(a,b,c){var d=a("./arrayLikeToArray");b.exports=function(a,b){if(a){if("string"===typeof a)return d(a,b);var c=Object.prototype.toString.call(a).slice(8,-1);"Object"===c&&a.constructor&&(c=a.constructor.name);if("Map"===c||"Set"===c)return Array.from(a);
if("Arguments"===c||/^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$/.test(c))return d(a,b)}}},{"./arrayLikeToArray":31}]},{},[10]);
